# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20170829_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
